server:
  port: 8182
  servlet:
    context-path: /ui
    session:
      cookie:
        name: UISESSION

security:
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8181/auth/oauth/token
      userAuthorizationUri: http://localhost:8181/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8181/auth/rest/principal

spring:
  thymeleaf:
    cache: false